<?php
// ============================================================
// DocsController – returns full ATI API spec as JSON
// GET /docs  (public, no auth required)
// ============================================================

class DocsController
{
    public static function spec(Request $req): void
    {
        $base = rtrim(
            (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http')
            . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost')
            . rtrim(dirname($_SERVER['SCRIPT_NAME'] ?? '/'), '/'),
            '/'
        );

        $spec = [
            'app'     => APP_NAME,
            'version' => APP_VERSION,
            'base_url'=> $base,
            'auth'    => [
                'type'   => 'Bearer Token (JWT HS256)',
                'header' => 'Authorization: Bearer <token>',
                'expiry' => '8 hours',
                'obtain' => 'POST /auth/login',
            ],
            'roles' => [
                'superadmin' => 'Full access – manage users, products, customers, quotations, payments',
                'editor'     => 'Accept/reject quotations, manage handover/returned status, record payments',
                'viewer'     => 'Read-only access to reports, inventory logs',
                'salesman'   => 'Browse products, submit quotation requests, view own quotes',
            ],
            'groups' => self::endpoints(),
        ];

        Response::success($spec);
    }

    // ── Endpoint definitions ──────────────────────────────────
    private static function endpoints(): array
    {
        return [

            // ─────────────────────────────────────────────────
            'System' => [
                [
                    'method'  => 'GET',
                    'path'    => '/health',
                    'summary' => 'API health check',
                    'detail'  => 'Returns API version and status. No authentication required.',
                    'auth'    => false,
                    'roles'   => [],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'message'=>'OK','data'=>['status'=>'ok','version'=>'1.0.0']],
                ],
            ],

            // ─────────────────────────────────────────────────
            'Authentication' => [
                [
                    'method'  => 'POST',
                    'path'    => '/auth/login',
                    'summary' => 'Login and obtain JWT token',
                    'detail'  => 'Pass email + password. Returns a signed JWT valid for 8 hours.',
                    'auth'    => false,
                    'roles'   => [],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'email',    'type'=>'string','required'=>true, 'description'=>'Registered email address'],
                        ['field'=>'password', 'type'=>'string','required'=>true, 'description'=>'Account password (min 6 chars)'],
                    ],
                    'body_ex' => ['email'=>'admin@ati.local','password'=>'Admin@1234'],
                    'resp_ex' => ['success'=>true,'message'=>'Login successful','data'=>['token'=>'eyJ0eX…','expires_in'=>28800,'user'=>['id'=>1,'name'=>'System Admin','email'=>'admin@ati.local','role'=>'superadmin']]],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/auth/me',
                    'summary' => 'Get current authenticated user',
                    'detail'  => 'Returns profile of the user whose JWT is in the Authorization header.',
                    'auth'    => true,
                    'roles'   => ['any authenticated user'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'message'=>'OK','data'=>['id'=>1,'name'=>'System Admin','email'=>'admin@ati.local','role'=>'superadmin','is_active'=>1,'created_at'=>'2026-03-02 20:57:03']],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/auth/refresh',
                    'summary' => 'Refresh JWT (issue a new token)',
                    'detail'  => 'Issues a fresh 8-hour token for the authenticated user without re-entering credentials.',
                    'auth'    => true,
                    'roles'   => ['any authenticated user'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'message'=>'OK','data'=>['token'=>'eyJ0eX…','expires_in'=>28800]],
                ],
            ],

            // ─────────────────────────────────────────────────
            'Users' => [
                [
                    'method'  => 'GET',
                    'path'    => '/users',
                    'summary' => 'List all users',
                    'detail'  => 'Paginated list of system users. Filter by role.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [
                        ['param'=>'role',     'type'=>'string', 'description'=>'Filter by role: superadmin | editor | viewer | salesman'],
                        ['param'=>'page',     'type'=>'int',    'description'=>'Page number (default: 1)'],
                        ['param'=>'per_page', 'type'=>'int',    'description'=>'Results per page (default: 20, max: 200)'],
                    ],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'message'=>'OK','data'=>['data'=>[['id'=>1,'name'=>'System Admin','email'=>'admin@ati.local','role'=>'superadmin','is_active'=>true]],'pagination'=>['page'=>1,'per_page'=>20,'total'=>1,'last_page'=>1]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/users',
                    'summary' => 'Create a new user',
                    'detail'  => 'Create a user with a role. Password will be bcrypt-hashed.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',     'type'=>'string','required'=>true,  'description'=>'Full name (max 150)'],
                        ['field'=>'email',    'type'=>'string','required'=>true,  'description'=>'Unique email address'],
                        ['field'=>'password', 'type'=>'string','required'=>true,  'description'=>'Password (min 8 chars)'],
                        ['field'=>'role',     'type'=>'string','required'=>true,  'description'=>'superadmin | editor | viewer | salesman'],
                    ],
                    'body_ex' => ['name'=>'Ali Hassan','email'=>'ali@ati.local','password'=>'Secret@123','role'=>'salesman'],
                    'resp_ex' => ['success'=>true,'message'=>'User created','data'=>['id'=>2]],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/users/{id}',
                    'summary' => 'Get a single user',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'message'=>'OK','data'=>['id'=>2,'name'=>'Ali Hassan','email'=>'ali@ati.local','role'=>'salesman','is_active'=>true]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/users/{id}',
                    'summary' => 'Update user fields',
                    'detail'  => 'All fields optional. Omit password to keep existing.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',      'type'=>'string', 'required'=>false,'description'=>'Full name'],
                        ['field'=>'email',     'type'=>'string', 'required'=>false,'description'=>'Email address'],
                        ['field'=>'password',  'type'=>'string', 'required'=>false,'description'=>'New password (min 8 chars)'],
                        ['field'=>'role',      'type'=>'string', 'required'=>false,'description'=>'superadmin | editor | viewer | salesman'],
                        ['field'=>'is_active', 'type'=>'boolean','required'=>false,'description'=>'Enable (true) or disable (false) the account'],
                    ],
                    'body_ex' => ['role'=>'editor','is_active'=>true],
                    'resp_ex' => ['success'=>true,'message'=>'User updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/users/{id}',
                    'summary' => 'Delete a user',
                    'detail'  => 'Cannot delete your own account.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Categories' => [
                [
                    'method'  => 'GET',
                    'path'    => '/categories',
                    'summary' => 'List all categories',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'message'=>'OK','data'=>[['id'=>1,'name'=>'Pharmaceuticals','created_at'=>'2026-03-02 20:57:03']]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/categories',
                    'summary' => 'Create a category',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name','type'=>'string','required'=>true,'description'=>'Unique category name (max 100)'],
                    ],
                    'body_ex' => ['name'=>'Vitamins & Supplements'],
                    'resp_ex' => ['success'=>true,'message'=>'Category created','data'=>['id'=>5]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/categories/{id}',
                    'summary' => 'Rename a category',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name','type'=>'string','required'=>true,'description'=>'New category name'],
                    ],
                    'body_ex' => ['name'=>'OTC Medicines'],
                    'resp_ex' => ['success'=>true,'message'=>'Category updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/categories/{id}',
                    'summary' => 'Delete a category',
                    'detail'  => 'Products in this category will have category_id set to NULL.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Products' => [
                [
                    'method'  => 'GET',
                    'path'    => '/products',
                    'summary' => 'List products (paginated)',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [
                        ['param'=>'category_id','type'=>'int',   'description'=>'Filter by category'],
                        ['param'=>'search',     'type'=>'string','description'=>'Search by name or product_code'],
                        ['param'=>'active',     'type'=>'int',   'description'=>'1 = active only, 0 = inactive only'],
                        ['param'=>'page',       'type'=>'int',   'description'=>'Page number'],
                        ['param'=>'per_page',   'type'=>'int',   'description'=>'Results per page (max 200)'],
                    ],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['data'=>[['id'=>1,'name'=>'Paracetamol 500mg','product_code'=>'ATI-20260302-1A2B3','category_name'=>'Pharmaceuticals','is_active'=>true]],'pagination'=>['page'=>1,'per_page'=>20,'total'=>1,'last_page'=>1]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/products',
                    'summary' => 'Create a product',
                    'detail'  => 'product_code is auto-generated (format: ATI-YYYYMMDD-XXXXX).',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',        'type'=>'string','required'=>true, 'description'=>'Product name (max 200)'],
                        ['field'=>'category_id', 'type'=>'int',  'required'=>false,'description'=>'Category ID'],
                        ['field'=>'description', 'type'=>'string','required'=>false,'description'=>'Optional description'],
                    ],
                    'body_ex' => ['name'=>'Paracetamol 500mg','category_id'=>1,'description'=>'Analgesic tablet'],
                    'resp_ex' => ['success'=>true,'message'=>'Product created','data'=>['id'=>1,'product_code'=>'ATI-20260302-1A2B3']],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/products/{id}',
                    'summary' => 'Get product with full variant/unit details',
                    'detail'  => 'Returns nested variants → units with current stock and pricing.',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['id'=>1,'name'=>'Paracetamol 500mg','product_code'=>'ATI-20260302-1A2B3','variants'=>[['id'=>1,'attributes'=>['strength'=>'500mg','form'=>'tablet'],'sku'=>'PARA-500-TAB','units'=>[['id'=>1,'unit_name'=>'piece','stock_quantity'=>500,'unit_price'=>5.00]]]]]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/products/{id}',
                    'summary' => 'Update product fields',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',        'type'=>'string', 'required'=>false,'description'=>'Product name'],
                        ['field'=>'category_id', 'type'=>'int',    'required'=>false,'description'=>'Category ID'],
                        ['field'=>'description', 'type'=>'string', 'required'=>false,'description'=>'Description'],
                        ['field'=>'is_active',   'type'=>'boolean','required'=>false,'description'=>'Active status'],
                    ],
                    'body_ex' => ['name'=>'Paracetamol 500mg Revised','is_active'=>true],
                    'resp_ex' => ['success'=>true,'message'=>'Product updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/products/{id}',
                    'summary' => 'Delete a product (cascades to variants)',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Product Variants' => [
                [
                    'method'  => 'GET',
                    'path'    => '/products/{productId}/variants',
                    'summary' => 'List variants for a product',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>[['id'=>1,'product_id'=>1,'attributes'=>['strength'=>'500mg'],'sku'=>'PARA-500-TAB','is_active'=>true]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/products/{productId}/variants',
                    'summary' => 'Add a variant to a product',
                    'detail'  => 'attributes is a free-form JSON object (e.g. {"size":"L","color":"red"}).',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'attributes','type'=>'object','required'=>true, 'description'=>'JSON key-value pairs describing the variant (size, color, strength, form, etc.)'],
                        ['field'=>'sku',       'type'=>'string','required'=>false,'description'=>'Optional unique stock-keeping unit code (max 100)'],
                    ],
                    'body_ex' => ['attributes'=>['strength'=>'500mg','form'=>'tablet'],'sku'=>'PARA-500-TAB'],
                    'resp_ex' => ['success'=>true,'message'=>'Variant created','data'=>['id'=>1]],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/variants/{id}',
                    'summary' => 'Get variant with nested units and stock',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['id'=>1,'product_name'=>'Paracetamol 500mg','attributes'=>['strength'=>'500mg'],'units'=>[['id'=>1,'unit_name'=>'piece','stock_quantity'=>500,'unit_price'=>5.00]]]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/variants/{id}',
                    'summary' => 'Update variant attributes or SKU',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'attributes','type'=>'object', 'required'=>false,'description'=>'Updated attribute JSON object'],
                        ['field'=>'sku',       'type'=>'string', 'required'=>false,'description'=>'New SKU'],
                        ['field'=>'is_active', 'type'=>'boolean','required'=>false,'description'=>'Active status'],
                    ],
                    'body_ex' => ['attributes'=>['strength'=>'500mg','form'=>'capsule'],'is_active'=>true],
                    'resp_ex' => ['success'=>true,'message'=>'Variant updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/variants/{id}',
                    'summary' => 'Delete a variant (cascades to variant-units)',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Units' => [
                [
                    'method'  => 'GET',
                    'path'    => '/units',
                    'summary' => 'List all sellable unit types',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>[['id'=>1,'name'=>'piece','multiplier'=>1.0],['id'=>2,'name'=>'box of 10','multiplier'=>10.0]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/units',
                    'summary' => 'Create a new unit type',
                    'detail'  => 'multiplier is the conversion factor to the base unit (e.g. "box of 10" has multiplier 10).',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',      'type'=>'string','required'=>true,'description'=>'Unique unit name (e.g. "box of 24")'],
                        ['field'=>'multiplier','type'=>'number','required'=>true,'description'=>'Conversion factor to base unit (must be > 0)'],
                    ],
                    'body_ex' => ['name'=>'box of 24','multiplier'=>24],
                    'resp_ex' => ['success'=>true,'message'=>'Unit created','data'=>['id'=>6]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/units/{id}',
                    'summary' => 'Update unit name or multiplier',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',      'type'=>'string','required'=>false,'description'=>'New unit name'],
                        ['field'=>'multiplier','type'=>'number','required'=>false,'description'=>'New multiplier'],
                    ],
                    'body_ex' => ['name'=>'strip of 10','multiplier'=>10],
                    'resp_ex' => ['success'=>true,'message'=>'Unit updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/units/{id}',
                    'summary' => 'Delete a unit type',
                    'detail'  => 'Will fail (409) if any variant is using this unit.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Variant–Units (Stock & Pricing)' => [
                [
                    'method'  => 'GET',
                    'path'    => '/variants/{variantId}/units',
                    'summary' => 'List units linked to a variant with stock and price',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>[['id'=>1,'unit_name'=>'piece','multiplier'=>1.0,'stock_quantity'=>500.0,'unit_price'=>5.00]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/variants/{variantId}/units',
                    'summary' => 'Link a unit to a variant and set price/stock',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'unit_id',       'type'=>'int',   'required'=>true, 'description'=>'ID of the unit to link'],
                        ['field'=>'unit_price',    'type'=>'number','required'=>true, 'description'=>'Selling price per unit'],
                        ['field'=>'stock_quantity','type'=>'number','required'=>false,'description'=>'Initial stock (default 0)'],
                    ],
                    'body_ex' => ['unit_id'=>1,'unit_price'=>5.00,'stock_quantity'=>500],
                    'resp_ex' => ['success'=>true,'message'=>'Variant-unit created','data'=>['id'=>1]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/variant-units/{id}',
                    'summary' => 'Update stock quantity or unit price',
                    'detail'  => 'Use this for manual stock adjustments. For audit-tracked movements use the quotation workflow.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'unit_price',    'type'=>'number','required'=>false,'description'=>'New selling price'],
                        ['field'=>'stock_quantity','type'=>'number','required'=>false,'description'=>'Corrected stock quantity'],
                    ],
                    'body_ex' => ['unit_price'=>5.50,'stock_quantity'=>480],
                    'resp_ex' => ['success'=>true,'message'=>'Variant-unit updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/variant-units/{id}',
                    'summary' => 'Unlink a unit from a variant',
                    'detail'  => 'Blocked (409) if there are quotation items referencing this variant-unit.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Customers' => [
                [
                    'method'  => 'GET',
                    'path'    => '/customers',
                    'summary' => 'List customers (paginated)',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [
                        ['param'=>'type',    'type'=>'string','description'=>'Filter by type: doctor | pharmacy | wholesaler | general'],
                        ['param'=>'search',  'type'=>'string','description'=>'Search by name, phone, or email'],
                        ['param'=>'page',    'type'=>'int',  'description'=>'Page number'],
                        ['param'=>'per_page','type'=>'int',  'description'=>'Per page (max 200)'],
                    ],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['data'=>[['id'=>1,'name'=>'Dr. Ahmed','type'=>'doctor','phone'=>'0300-1234567']],'pagination'=>['page'=>1,'per_page'=>20,'total'=>1,'last_page'=>1]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/customers',
                    'summary' => 'Create a customer record',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',   'type'=>'string','required'=>true, 'description'=>'Full name (max 150)'],
                        ['field'=>'type',   'type'=>'string','required'=>true, 'description'=>'doctor | pharmacy | wholesaler | general'],
                        ['field'=>'phone',  'type'=>'string','required'=>false,'description'=>'Contact phone'],
                        ['field'=>'email',  'type'=>'string','required'=>false,'description'=>'Contact email'],
                        ['field'=>'address','type'=>'string','required'=>false,'description'=>'Full address'],
                    ],
                    'body_ex' => ['name'=>'Dr. Ahmed Khan','type'=>'doctor','phone'=>'0300-1234567','email'=>'ahmed@clinic.pk'],
                    'resp_ex' => ['success'=>true,'message'=>'Customer created','data'=>['id'=>1]],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/customers/{id}',
                    'summary' => 'Get customer with last 10 invoices',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['id'=>1,'name'=>'Dr. Ahmed Khan','type'=>'doctor','recent_invoices'=>[['id'=>1,'date'=>'2026-03-02','total_amount'=>'2500.00','paid'=>'1000.00','due'=>'1500.00']]]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/customers/{id}',
                    'summary' => 'Update customer info',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'name',   'type'=>'string','required'=>false,'description'=>'Full name'],
                        ['field'=>'type',   'type'=>'string','required'=>false,'description'=>'Customer type'],
                        ['field'=>'phone',  'type'=>'string','required'=>false,'description'=>'Phone'],
                        ['field'=>'email',  'type'=>'string','required'=>false,'description'=>'Email'],
                        ['field'=>'address','type'=>'string','required'=>false,'description'=>'Address'],
                    ],
                    'body_ex' => ['phone'=>'0321-9876543','type'=>'pharmacy'],
                    'resp_ex' => ['success'=>true,'message'=>'Customer updated','data'=>null],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/customers/{id}',
                    'summary' => 'Delete a customer',
                    'detail'  => 'Blocked (409) if customer has invoices.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Quotation Requests' => [
                [
                    'method'  => 'GET',
                    'path'    => '/quotations',
                    'summary' => 'List quotation requests',
                    'detail'  => 'Salesmen see only their own. Editors/admins see all. Filter by status or salesman.',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [
                        ['param'=>'status',     'type'=>'string','description'=>'pending | accepted | returned | rejected'],
                        ['param'=>'salesman_id','type'=>'int',  'description'=>'Filter by salesman user ID (editors/admins only)'],
                        ['param'=>'page',       'type'=>'int',  'description'=>'Page number'],
                        ['param'=>'per_page',   'type'=>'int',  'description'=>'Per page'],
                    ],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['data'=>[['id'=>1,'status'=>'pending','salesman_name'=>'Ali Hassan','note'=>'Urgent order']],'pagination'=>['page'=>1,'per_page'=>20,'total'=>1,'last_page'=>1]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/quotations',
                    'summary' => 'Submit a new quotation request',
                    'detail'  => 'Salesmen submit requests. unit_price is snapshotted from current variant_units price.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor','salesman'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'items',       'type'=>'array', 'required'=>true, 'description'=>'Array of {variant_unit_id, quantity} objects'],
                        ['field'=>'customer_id', 'type'=>'int',   'required'=>false,'description'=>'Pre-select a customer (editors can also set on accept)'],
                        ['field'=>'note',        'type'=>'string','required'=>false,'description'=>'Optional note for the editor'],
                    ],
                    'body_ex' => ['items'=>[['variant_unit_id'=>1,'quantity'=>50],['variant_unit_id'=>3,'quantity'=>10]],'note'=>'Urgent – needed by Friday'],
                    'resp_ex' => ['success'=>true,'message'=>'Quotation created','data'=>['id'=>1]],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/quotations/{id}',
                    'summary' => 'Get quotation with full item details',
                    'detail'  => 'Salesmen can only fetch their own quotations.',
                    'auth'    => true,
                    'roles'   => ['all roles'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['id'=>1,'status'=>'pending','items'=>[['id'=>1,'product_name'=>'Paracetamol 500mg','unit_name'=>'piece','quantity'=>50,'unit_price'=>5.00]]]],
                ],
                [
                    'method'  => 'PUT',
                    'path'    => '/quotations/{id}/status',
                    'summary' => 'Accept / Reject / Return a quotation',
                    'detail'  => 'ACCEPT: deducts stock from variant_units, logs "handover", creates a sales invoice. RETURN: reverses stock, logs "returned", marks invoice returned. REJECT: status change only. customer_id required when accepting.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'status',      'type'=>'string','required'=>true, 'description'=>'accepted | rejected | returned'],
                        ['field'=>'customer_id', 'type'=>'int',   'required'=>false,'description'=>'Customer ID – REQUIRED when status = accepted'],
                    ],
                    'body_ex' => ['status'=>'accepted','customer_id'=>1],
                    'resp_ex' => ['success'=>true,'message'=>'Quotation accepted; stock deducted and invoice created','data'=>['quotation_id'=>1,'invoice_id'=>1,'total_amount'=>250.00]],
                ],
            ],

            // ─────────────────────────────────────────────────
            'Invoices' => [
                [
                    'method'  => 'GET',
                    'path'    => '/invoices',
                    'summary' => 'List invoices with payment summary',
                    'detail'  => 'Every row includes total_amount, paid (sum of payments), and outstanding due.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [
                        ['param'=>'customer_id','type'=>'int',   'description'=>'Filter by customer'],
                        ['param'=>'from',       'type'=>'date',  'description'=>'Start date (YYYY-MM-DD)'],
                        ['param'=>'to',         'type'=>'date',  'description'=>'End date (YYYY-MM-DD)'],
                        ['param'=>'status',     'type'=>'string','description'=>'active | returned | void'],
                        ['param'=>'page',       'type'=>'int',   'description'=>'Page number'],
                        ['param'=>'per_page',   'type'=>'int',   'description'=>'Per page'],
                    ],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['data'=>[['id'=>1,'customer_name'=>'Dr. Ahmed','date'=>'2026-03-02','total_amount'=>250.00,'paid'=>100.00,'due'=>150.00,'status'=>'active']],'pagination'=>['page'=>1,'per_page'=>20,'total'=>1,'last_page'=>1]]],
                ],
                [
                    'method'  => 'GET',
                    'path'    => '/invoices/{id}',
                    'summary' => 'Get invoice with line items and payment history',
                    'detail'  => 'Includes the full item breakdown from the quotation and all payment rows recorded against this invoice.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['id'=>1,'customer_name'=>'Dr. Ahmed','date'=>'2026-03-02','total_amount'=>250.00,'paid'=>100.00,'due'=>150.00,'items'=>[['product_name'=>'Paracetamol','unit_name'=>'piece','quantity'=>50,'unit_price'=>5.00,'line_total'=>250.00]],'payments'=>[['id'=>1,'amount_paid'=>100.00,'payment_date'=>'2026-03-02','method'=>'cash']]]],
                ],
            ],

            // ─────────────────────────────────────────────────
            'Payments' => [
                [
                    'method'  => 'GET',
                    'path'    => '/invoices/{invoiceId}/payments',
                    'summary' => 'List payments for an invoice',
                    'detail'  => 'Also returns total_amount, total_paid, and outstanding due for quick reference.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['invoice_id'=>1,'total_amount'=>250.00,'total_paid'=>100.00,'due'=>150.00,'payments'=>[['id'=>1,'amount_paid'=>100.00,'payment_date'=>'2026-03-02','method'=>'cash','reference'=>null]]]],
                ],
                [
                    'method'  => 'POST',
                    'path'    => '/invoices/{invoiceId}/payments',
                    'summary' => 'Record a (partial) payment against an invoice',
                    'detail'  => 'Multiple payments are allowed per invoice. Over-payment is blocked. Returns updated running totals.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor'],
                    'query'   => [],
                    'body'    => [
                        ['field'=>'amount_paid',  'type'=>'number','required'=>true, 'description'=>'Amount received (must be > 0 and ≤ outstanding due)'],
                        ['field'=>'payment_date', 'type'=>'date',  'required'=>true, 'description'=>'Date of payment (YYYY-MM-DD)'],
                        ['field'=>'method',       'type'=>'string','required'=>false,'description'=>'cash | bank_transfer | cheque | etc.'],
                        ['field'=>'reference',    'type'=>'string','required'=>false,'description'=>'Cheque/transaction number or reference'],
                        ['field'=>'note',         'type'=>'string','required'=>false,'description'=>'Any additional notes'],
                    ],
                    'body_ex' => ['amount_paid'=>150.00,'payment_date'=>'2026-03-05','method'=>'bank_transfer','reference'=>'TXN-20260305-001'],
                    'resp_ex' => ['success'=>true,'message'=>'Payment recorded','data'=>['id'=>2,'total_paid'=>250.00,'due'=>0.00]],
                ],
                [
                    'method'  => 'DELETE',
                    'path'    => '/payments/{id}',
                    'summary' => 'Delete a payment record',
                    'detail'  => 'Superadmin only. Use with caution — deleting a payment increases the invoice due amount.',
                    'auth'    => true,
                    'roles'   => ['superadmin'],
                    'query'   => [],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => null,
                ],
            ],

            // ─────────────────────────────────────────────────
            'Inventory Log' => [
                [
                    'method'  => 'GET',
                    'path'    => '/inventory/log',
                    'summary' => 'Audit trail of all stock movements',
                    'detail'  => 'Every handover, return, and sale is logged with user, timestamp and related quotation/invoice ID. Filter by any combination of the query params.',
                    'auth'    => true,
                    'roles'   => ['superadmin','editor','viewer'],
                    'query'   => [
                        ['param'=>'action',         'type'=>'string','description'=>'handover | sold | returned'],
                        ['param'=>'variant_unit_id','type'=>'int',  'description'=>'Filter by specific variant-unit'],
                        ['param'=>'product_id',     'type'=>'int',  'description'=>'Filter by product'],
                        ['param'=>'user_id',        'type'=>'int',  'description'=>'Filter by the user who triggered the movement'],
                        ['param'=>'from',           'type'=>'date', 'description'=>'Start date (YYYY-MM-DD)'],
                        ['param'=>'to',             'type'=>'date', 'description'=>'End date (YYYY-MM-DD)'],
                        ['param'=>'page',           'type'=>'int',  'description'=>'Page number'],
                        ['param'=>'per_page',       'type'=>'int',  'description'=>'Per page (max 200)'],
                    ],
                    'body'    => null,
                    'body_ex' => null,
                    'resp_ex' => ['success'=>true,'data'=>['data'=>[['id'=>1,'action'=>'handover','quantity'=>-50.0,'product_name'=>'Paracetamol 500mg','unit_name'=>'piece','user_name'=>'System Admin','created_at'=>'2026-03-02 21:00:00']],'pagination'=>['page'=>1,'per_page'=>50,'total'=>1,'last_page'=>1]]],
                ],
            ],

        ];
    }
}
